---
baselinux_hostname: "{{ inventory_hostname }}"
baselinux_timezone: "UTC"
baselinux_selinux_mode: "permissive"

baselinux_root_passwd: "explorium"

baselinux_sshd_port: "22"
baselinux_sshd_logingracetime: "60m"
baselinux_sshd_permitrootlogin: "yes"
baselinux_sshd_maxauthtries: "6"
baselinux_sshd_pubkeyauthentication: "yes"
baselinux_sshd_passwordauthentication: "yes"
baselinux_ssh_stricthostkeychecking: "no"
baselinux_ssh_userknownhostsfile: "/dev/null"

baselinux_figlet_string: "Ansible"

baselinux_pkgs:
  - vim
  - ansible
  - wget
  - mlocate
  - chrony
  - htop
  - figlet
  - jq
  - telnet
  - nmap
  - bash-completion
  - bind-utils
  - curl
  - net-tools
  - git
  - sysstat
  - lsof
